name: cpp

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_TYPE: Release
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install conan
      run: pip install conan
    - name: Build
      run: |
        mkdir build
        cd build
        conan profile update settings.compiler.libcxx=libstdc++11 default
        conan install ..
        cmake ..
        make
