name: cpp

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_TYPE: Release
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: |
        mkdir build
        cd build
        conan install ..
        cmake ..
        make
